### ISSUE TITLE
Does not work in 8.7.9

### ISSUE THREAD

**Issue by bytesinmotion** [arndtteunissen/simple_404_handler#4]
Hi,

I just installed the extension from repository (1.0.5) configured and get this when trying it out:

Oops, an error occurred!
Error: 404 page by USER_FUNCTION "Arndtteunissen\Simple404Handler\UserFunc\Page->pageNotFound" failed.
More information regarding this error might be available online.

**Comment by jdoubleu** [comment]
Do you have any Exception-Trace you can provide to help us identify the cause.

Are you sure you are using TYPO3 8.7.8?
I probably found the exit point where the exception gets thrown, but its in TYPO3 `8.7.9`.

It has something todo with the GeneralUtility not being able to call the user function in [\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController:1998](https://github.com/TYPO3/TYPO3.CMS/blob/v8.7.9/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php#L1998)

**Comment by bytesinmotion** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/29398157/34871350-9d05f684-f78d-11e7-9076-1edb1d2a470a.png)

**Comment by jdoubleu** [comment]
As I expected your TYPO3 version 8.7.9 (compare with class path in exception).

The screenshot you provided shows only the call-stack and not the exception trace. Is there a log file in your `typo3temp/var/logs` folder with this exception logged?

I'm trying to reproduce the exception on a standalone installation with the `typo3_introduction` package.

**Comment by bytesinmotion** [comment]
Nope, is there an option I have to set to get that log?

Maybe it has something to do with Realurl?

**Comment by jdoubleu** [comment]
You could either change the `[SYS][systemLog]` config in your `AdditionalConfiguration.php` or select the "Live" Configuration Preset in the `Install Tool > Configuration Presets > Debug settings`.

However I just released the version `1.0.6`. Could you update your package?
There was a bugfix which _COULD_ have caused the exception in your case.

If it doesn't help I really need the exception-trace to identify the cause because I couldn't reproduce the error in my local environment with a standalone TYPO3 installation.

**Comment by jdoubleu** [comment]
@bytesinmotion do you have any updates on this? Does it work after the update?

**Comment by bytesinmotion** [comment]
Sorry, I was in a hurry to deploy the website and I choose a different extension :(

**Comment by jdoubleu** [comment]
Okay, but thank you for your participation!
